# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.arloesol.eu
title: Arloesol
author: John Arloesol
description: > # "this text appears in head meta for Google search
  IT services and consulting
copyright: 'Copyright &copy; <script>document.write(/\d{4}/.exec(Date())[0])</script>. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    icon: twitter
    url: https://twitter.com/arloesol
  - title: github
    icon: github
    url: https://github.com/arloesol
  - title: linkedin
    icon: linkedin
    url: https://www.linkedin.com/company/arloesol
  - title: email
    icon: envelope
    url: mailto:info@arloesol.eu
